### ISSUE TITLE
META : Tracking Homepage Last Minute Changes

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#189]
This is just an issue to track other issues making changes to the homepage before launch, e.g. adding or removing sections.

- [ ] #35 Get Ecosystem visualization  up and link to new sub-page on the topic in About
- [ ] #183 More Info buttons on Homepage sections
- [ ] #188 New "Breaking down data silos" section
- [ ] #190 Merge Specifications Sections on Homepage
- [ ] #193 Simple figures explaining most important steps of how OSLC is used for data integration and data interoperability
- [ ] more to come... ?

Home page ideas discussed a while ago here:
https://docs.google.com/document/d/1Ya5Mid8Nlg7Te0ikdIaJ5vZ_xqCjF3KoTremxGi1n5A/edit

**Comment by gabrielfdac** [comment]
Already done, closing
