### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by gabrielfdac** [OSLC/oslc-site-hugo#199]
This is a list of everything we should get done before Launch, and some things we should make sure are working post launch.

### Non-Content Related Issues
- [x] #192: Unpublish oslc.github.io pages and create production branch;
- [x] #173: New Facebook ID;
- [x] #169: Content Handlers and Redirects;
- [x] #200: Hang on Page Load;
- [x] #203: Improve categories on News;
- [x] #205: Style/JS and Lazy Loading images
- [x] #209: Overall Improvements;
- [x] #210: Mobile Improvements;

### Content Issues
- [x] #185: More FAQ questions;
- [ ] #100: Terms of Use page;
- [ ] #159: Implementations page;
- [x] #193: How OSLC works images;
- [x] #198: New Homepage Design/Content;
- [x] #208: About Page Restructure;

### Uncertain Issues
_Progress or Necessity of these issues needs to be double checked_
- [x] #16: Namespace/Vocabularies page;
- [x] #194: Create archive for vocabularies page;

## Post Launch
- [x] Make sure resources are served properly;
- [x] Check for redirects;
- [x] Check Social Media sharing;
- [x] HTTPS;
- [x] Investigate possible load times issues;
- [ ] Double check if documentation for adding content to the site is properly filled out;
- [ ] Check for SEO problems/improvements;

## Issues Pushed Back
#116: Gather case studies content;
#101: Privacy Policy page;
#77: Document how to create site content;
#197: Google Analytics;
#177: OSLC Examples(Could go well on Why OSLC? page);
#115: Gather testimonials for about;
#187: Getting Started page (possibly a sub page);

This list a reflection of [this](https://docs.google.com/document/d/1f7GRDMR7kml49bm1C-m5THkeft7ZOfOCGucp-GwwXvM/) document. Therefore this issue is a way to better track the progression of the issues listed in the document.

Please feel free to add more to the list of check the ones as they're completed
